image: maven:3.8.5-openjdk-17

variables:
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""
  MAVEN_CLI_OPTS: "-s ci_settings.xml --batch-mode"
  DOCKER_IMAGE: "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"

  
stages:
  - docker-build

Docker Build:
  stage: docker-build
  image: docker:19-dind
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --tag $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE