image: maven:3.8.5-openjdk-17

variables:
  SPRING_PROFILES_ACTIVE: gitlab-ci 

services:
  - name: mysql:latest
    alias: mysql
    variables:
      MYSQL_ROOT_PASSWORD: "root"  
      MYSQL_DATABASE: "sparesti"

cache:
  key: "${CI_COMMIT_REF_SLUG}" # Branch-specific cache keys to have separate caches across branches.
  paths:
    - .m2/repository
  
stages:
  - install
  - build
  - test
  - generate_site_reports
  - modify_generated_site_reports
  - publish_pages

install_dependencies:
  stage: install
  script:
    - mvn dependency:go-offline
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .m2/repository
    policy: push

build_project:
  stage: build
  script:
    - mvn clean install -DskipTests
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .m2/repository
    policy: pull

test_project:
  stage: test
  script:
    - mvn test 
  when: always
  artifacts:
    expire_in: 1 day
    paths:
      - target/site/jacoco
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml
  cache:
    key: "${CI_COMMIT_REF_SLUG}"
    paths:
      - .m2/repository
    policy: pull

generate_site_reports:
  stage: generate_site_reports
  script:
    - mvn site # Generates a website containing project documentation (including checkstyle report)
  artifacts:
    paths:
      - target/site/
  only:
    - master

modify_generated_site_reports: # Modify the generated website containing project documentation to also link to JaCoCo coverage file
  image: python:3.8-slim
  stage: modify_generated_site_reports
  script:
    - pip install beautifulsoup4 # Used to parse contents of HTML files
    - python scripts/add_jacoco_coverage_link_to_html.py # Script that modifies the HTML file to include a link to JaCoCo coverage file
  artifacts:
    paths:
      - target/site/
  dependencies:
    - generate_site_reports
  only:
    - master

# We move the code coverage reports generated by jacoco and mvn site to be served by Gitlab Pages (Settings -> Pages)
pages:
  image: alpine:latest
  stage: publish_pages
  dependencies:
    - modify_generated_site_reports
  script:
    - mkdir public
    - cp -r target/site/* public/
  artifacts:
    paths:
      - public
  only:
    - master       
