variables:
  MAVEN_CLI_OPTS: "-s ci_settings.xml --batch-mode"
  DOCKER_IMAGE: "testimage"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: "tcp://docker:2375"

stages:
  - docker-build
  - deploy

deploy:
  stage: deploy
  image: ubuntu:latest
  before_script:
    - apt-get -yq update
    - apt-get -yqq install ssh
    - apt-get install sshpass
  script: 
    - sshpass -p sParest1en ssh -v -o StrictHostKeyChecking=no root@128.199.53.153 "docker kill backend && docker run -d --name backend registry.gitlab.com/henrikberg/sparesti-registry:backend"

