server:
  port: 8080

spring:
  profiles:
    active: no-flyway
  mail:
    host: smtp.gmail.com
    port: 587
    username: sparesti050@gmail.com
    password: cdxdjzkwapkbitej
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:mysql://mysql:3306/sparesti
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
  sql:
    init:
      mode: always

springdoc:
  swagger-ui:
    path: /swagger/index.html
  api-docs:
    path: /swagger/api-docs
