server.port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sparesti
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        '[format_sql]': true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      continue-on-error: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: sparesti050@gmail.com
    password: cdxdjzkwapkbitej
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

springdoc:
  swagger-ui:
    path: /swagger/index.html
  api-docs:
    path: /swagger/api-docs