package no.ntnu.idi.stud.savingsapp.model.configuration;

public enum ChallengeType {

  NO_COFFEE,
  NO_CAR,
  SHORTER_SHOWER,
  SPEND_LESS_ON_FOOD,
  BUY_USED_CLOTHES,
  LESS_SHOPPING,
  DROP_SUBSCRIPTION,
  SELL_SOMETHING,
  BUY_USED,
  EAT_PACKED_LUNCH,
  STOP_SHOPPING,
  ZERO_SPENDING,
  RENT_YOUR_STUFF,
  MEATLESS,
  SCREEN_TIME_LIMIT,
  UNPLUGGED_ENTERTAINMENT,
}
