# This script adds a link to the JaCoCo coverage report in an HTML file.
def add_jacoco_link_to_site_report(file_path):
    import bs4

    # Read the HTML file
    with open(file_path, 'r', encoding='utf-8') as file:
        html_content = file.read()

    # Use Beautiful Soup to parse the HTML content
    soup = bs4.BeautifulSoup(html_content, 'html.parser')
    
    # Find the navigation list in the HTML that contains links like 'Checkstyle'
    # We assume there is a <ul> element under an <li> classed 'active'
    nav_list = soup.find("li", class_="active").find("ul", class_="nav nav-list")
    
    # Create a new link item for the JaCoCo report
    new_li = soup.new_tag("li")
    new_a = soup.new_tag("a", href="jacoco/index.html")
    new_a.string = "Jacoco Coverage" # Text that will be displayed for the link
    new_li.append(new_a) # Add the link to the list item
    
    # Add the new list item to the navigation list
    nav_list.append(new_li)

    # Find the table that contains the Checkstyle link
    report_table = soup.find("table", class_="table table-striped")    

    # Create a new row for the table with two columns: 
    # one for the link and one for the description
    new_row = soup.new_tag("tr")
    column1 = soup.new_tag("td")
    column2 = soup.new_tag("td")
    link_in_table = soup.new_tag("a", href="jacoco/index.html")
    link_in_table.string = "JaCoCo Coverage"
    column1.append(link_in_table)
    column2.string = "Code coverage report generated by JaCoCo."
    
    # Add both columns to the row
    new_row.append(column1)
    new_row.append(column2)
    
    # Add the new row to the table
    report_table.append(new_row)
    
    # Save the changes by writing back to the same HTML file
    with open(file_path, 'w', encoding='utf-8') as file:
        file.write(soup.prettify())  # Use prettify to make the HTML look nice

file_path = 'target/site/project-reports.html'
add_jacoco_link_to_site_report(file_path)
